import { Plus_Jakarta_Sans, Geist_Mono, Inter, Outfit, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ChatBot from "@/components/chat/ChatBot";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakarta.variable} ${inter.variable} ${outfit.variable} ${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <ChatBot />
        </Providers>
      </body>
    </html>
  );
}